name: "sonar_cloud_scan_github_actions"

on:
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
 build:
  runs-on: ubunto-latest
  steps:
    - uses: actions/checkout@v3
      with: 
           fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
         args: >
            -Dsonar.projectKey=sonarqude
            -Dsonar.organization="sonarqude"
            -Dsonar.python.coverage.reportPaths=coverage.xml

